import type { Metadata } from "next";
import { Anuphan } from "next/font/google";
import React from "react";
import { GoogleAnalytics } from "@next/third-parties/google";

import "./globals.css";

const anuphan = Anuphan({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>CU-TU 2024</title>
        <link rel="icon" href="/user/logo.svg" sizes="any" />
      </head>
      <body className={anuphan.className}>{children}</body>

      <GoogleAnalytics gaId="G-96K5LPMG23" />
    </html>
  );
}
