version: '3.9'

services:
  redis:
    image: redis:7.2.4-bookworm
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
  api:
    image: mcr.microsoft.com/devcontainers/go:1-1.22-bookworm
    container_name: api
    command: sleep infinity
    volumes:
      - ../:/workspace