name: 'CI'

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/isd-sgcu/cutu2024-backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: apps/server
          tags: ${{ env.IMAGE_NAME }}:${{ github.ref_type == 'tag' && github.ref_name ||  github.sha }},${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=gha,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
