name: 'CI'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build api go application
        env:
          CGO_ENABLED: 0
          GOOS: linux
        run: cd apps/api && go build -o api ./... && cp api ../..

      - name: Build admin-api go application
        env:
          CGO_ENABLED: 0
          GOOS: linux
        run: cd apps/admin-api && go build -o admin_api ./... && cp admin_api ../..

      - uses: actions/upload-artifact@v3
        with:
          name: api
          path: api

      - uses: actions/upload-artifact@v3
        with:
          name: admin_api
          path: admin_api
