name: 'CI'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build api go application
        env:
          CGO_ENABLED: 0
          GOOS: linux
        run: go build -C apps/api -o api ./... && cp apps/api/api .

      - name: Build admin-api go application
        env:
          CGO_ENABLED: 0
          GOOS: linux
        run: go build -C apps/admin_api -o admin_api ./... && cp apps/admin_api/admin_api .

      - uses: actions/upload-artifact@v3
        with:
          name: api
          path: api

      - uses: actions/upload-artifact@v3
        with:
          name: admin_api
          path: admin_api
